site_name: Techable Words

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
  palette:
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light node

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - attr_list

nav:
  - 'Home':
    - index.md
  - 'GitHub':
    - gh/index.md
  - 'MKDocs':
    - mmd/index.md